import os

files = ['assets/site/build-site.py', 'scripts/build-site.py']
for f in files:
    with open(f, 'r') as file:
        content = file.read()
    
    # Replace strings in page_shell
    content = content.replace('— noteout</title>', '— Digital Garden</title>')
    content = content.replace('content="noteout — take your thoughts out"', 'content="Digital Garden"')
    content = content.replace('<h1 class="site-title">noteout</h1>', '<h1 class="site-title">Digital Garden</h1>')
    content = content.replace('<p class="tagline">take your thoughts out</p>', '<p class="tagline">a personal digital garden</p>')
    content = content.replace('<footer class="site">noteout &mdash; take your thoughts out</footer>', '<footer class="site">Digital Garden</footer>')
    
    # Replace strings in build_index
    content = content.replace("page_shell('noteout',", "page_shell('Digital Garden',")
    
    # Replace strings in build_readme
    content = content.replace("'# noteout',", "'# Digital Garden',")
    content = content.replace("'take your thoughts out',", "'a personal digital garden',")
    content = content.replace("'*generated by noteout — take your thoughts out*',", "'*generated by noteout — a digital garden*',")
    
    with open(f, 'w') as file:
        file.write(content)

print("Patched successfully!")
